[id="introduction"]

= Introducción a Starknet

Bienvenido al Starknet Book. Este es tu camino para entender las caracasteristicas fudnamentales de Starknet, su filosofia y su lenguaje único, Cairo. Bien seas un desarrollador, un entusiasta cripto o apenas estas llegando a este mundo, este libro es tu punto de partida. 

== ¿Qué es Starknet?

Starknet es una red de capa 3 que hace a las transacciones en Ethereum mas rápidas, mas economicas y mucho mas seguras a traves del uso de la tecnologia zk-STARKs. Piensa en ella como una capa mejorada sobre Ethereum optimizada en velocidad y costos.

=== Caracteristicas clave.

Estas son algunas de las caracateristicas importantes de Starknet:

* Bajo Costo: Las transacciones en Starknet cuestan menos que en Ethereum. Proximas actualizaciones y mejoras como lo son Volition y la implementación EIP 4844 las harán aún mas economicas. 
* Plataforma amigable con los desarrolladores: Starknet le permite a los desarrolladores construir aplicaciones descentralizadas usando su lenguaje nativo Cairo.
* Rápidez y eficiencia:  Proximos lanzamientos apuntan a transacciones mas rápidas y economicas. 
* CMV: Gracias a Cairo, Starknet ejecuta su propia maquina virtual. La Cairo VM (CVM), lo que nos permite innovar mas allá de la maquina virtual de Ethereum (EVM) y crear nuevos paradigmas para las aplicaciones descentralizadas. 

Algunos de ellos son:

* Abstracción de cuentas (AA): Implementada a nivel de protocolo, facilita diversos esquemas de firma asegurando la seguridad y la custodia de activos.
* *Volition*: Será implementado en la testnet en el Q4 de 2023, permitirá a los desarrolladores regutlas la disponibilidad de datos en Ethereum (L1) o en Starknet (L2). Reducir la cantidad de datos en la L1 reducirá radicalmente los costos.
* Paymaster: Starknet permitirá a los usuarios elegir como pagas la comisión de las transacciones, siguiendo los lineamientos propuestos en la EIP-4337 y permitiendo a la transacción indicar un contrato especifico, se crea un Paymaster para pagar la transacción. Proveyendo transacciones sin gas, mejorando la accesibilidad del usuario. 

== Filosofia de Starknet: Creada para desarrolladores.

Todo en Starknet esta diseñado pára ser amigable para los desarrolladores. Es una plataforma de alto rendimiento diseñada para construir aplicaciones descentralizadas potentes de forma facil. Estas son sus bases:

* Velocidad y costos: Rápidas transacciones y bajos costos de comisión, la hacen ideal para aplicaciones de alto consumo de recursos. 
* Cairo: Este lenguaje en evolución facilita el uso de *validity proof* y tecnologia *zk-STARKs* .
* Comunidad: Comunicación activa con los desarrolladores a traves de Telegram y Discord.
* Libertad: No mas limitaciones tecnlogicas. Construye lo que siempre has querido. 
* Herramientas: Un conjunto completo de herramientas de desarrollo, incluyendo multiples SDKs y frameworks para *testing*.

La filosofia que guia la ruta de Starknet:

== Cairo: El lenguaje de Starknet

Caito esta diseñado par crear contratos inteligentes basados en STARK. Como lenguaje nativo de Starknet, es la base para contruir aplicaciones descentralizadas seguras y escalables. Si quieres aprenderlo a fondo recurre al https://cairo-book.github.io/es/[Cairo Book en español] y a https://github.com/shramee/starklings-cairo1[Starklings].

Inspirado en Rust, Cairo permite crear contratos de forma rápida, segura y comoda. 

=== ¿Por qué elegir Cairo?

Cairo esta diseñado para un nuevo paradigma llamado 'Computación demostrable', el cual permite a los programas probar que su ejecución fue correcta sin requerir correrlo nuevamente. He aquí por qué se destaca:

* Proposito único: Diseñado especificamente para contratos inteligentes.
* Sin los limites de la EVM: Va más allá de lo que puede hacer la máquina virtual Ethereum.
* Flexibilidad: Usa traits para mejorar la flexibilidad en vez de herencia.

== Gobernanza

La Fundación Starknet supervisa la gobernanza en Starknet. Sus responsabilidades incluyen:

* Manejo de las operaciones y desarrollos en Starknet.
* Supervisar la DAO de Starknet, permitiendo la participación de la comunidad.
* Estableciendo reglas para mantener la integridad de la red. 


Nos enfocamos en los aportes técnicos y el debate para mejorar el protocolo. Si bien valoramos todas las perspectivas, son los conocimientos técnicos los que nos permiten avanzar.

Los miembros pueden influir en Starknet votando por cambios. Aquí el proceso: 

* Se libera una nueva versión de prueba en la red de Goerli. 
* Los miembros tienen seis dias para revisarla. 
* Se crea una propuesta y la comunidad vota.
* Si la mayoria vota 'SI' entonces se actualiza la red principal.

En resumen, la gobernanza en la clave para la evolución de Starknet.

Las mejoras son propuestas creando un SNIP (StarkNet Improvement Proposals).

=== SNIP: Propuestas de mejoras en Starknet

SNIP es la abreviación de *StarkNet Improvement Proposal* en ingles. Es esencialmente un plano detalladao de la mejora propuesta o cambio en el ecosistema de Starknet. Un SNIP bien construido incluye tanto especificaciones tecnicas del cambio así como los motivos detras de ellos. Si estás proponiendo un SNIP, es tu deber buscar el apoyo de la comunidad y documentar las objeciones (para mas detalles https://community.starknet.io/t/draft-simp-1-simp-purpose-and-guidelines/1197#what-is-a-snip-2[aquí]). Una vez que un SNIP es aprobado se vuelve parte del protocolo de Starknet. Todos los SNIPs estan publicados en https://github.com/starknet-io/SNIPs[este repositorio].

Los SNIPs cumplen tres papeles cruciales:

1. Son la via para proponer mejoras o cambios.
2. Funcionan como una plataforma de discusión tecnica dentro de la comunidad.
3. Documentan todo el proceso de toma de decisiones, ofreciendo un historico de la evolución de Starknet.

Como los SNIPs son guardados en como archivos de texto en un https://github.com/starknet-io/SNIPs[repositorio con control de versiones], puedes facilmente seguir los cambios y entender el historial de cada propuesta.

Para aquellos que están construyento en Starknet, los SNIPs no son solo recomendaciones, son una hoja de ruta. Es importante para los implementadores mantener una lista de los SNIP que han ejecutado. Esta transparencia ayuda a los usuarios a conocer el estado de una implementación particular o libreria.

== Desarrollo

La Fundación Starknet nutre activamente al ecosistema a través de:

* Dar soporte a investigación y desarrollo.
* Promoviendo la adopción de las tecnologias de Starknet.
* Financiando y organizando conferencias y eventos.

=== Participación de la comunidad

La fuerza de la comunidad es importante para la Fundación. Para fomentar el compromiso la Fundación Starknet:

* Organiza eventos y discusiones.
* Colabora con comunidades aliadas en blockchain.
* Crea vías para que la comunidad contribuya al crecimiento de Starknet.

== ¿Qué es Starkware?

Starkware, fue fundada en 2018 esta enfocada en la tecnología zk-STARK. Entre sus productos clave encontramos:

* StarkEx: Una solución eficiente de Capa 2 sobre Ethereum, basada en pruebas STARK.
* Cairo: Un lenguaje de programación de código abierto diseñado para eficiencia en aplicaciones descentralizadas (https://github.com/starkware-libs/cairo/tree/73c3ed0a1af65f53490866426ae49360b2304374[mira su repositorio].)

Starknet en sus ultimos proyectos, apunta a una evolución impulsada por la comunidad bajo la gobernanza de la Fundación Starknet.

== Recursos de apendizaje

Para profundizar en Starknet y Cairo:

* https://book.starknet.io[El Starknet Book]: Para dominar Starknet
* https://cairo-book.github.io/es[Con el Cairo Book en español]: dominaras Cairo.
* https://github.com/shramee/starklings-cairo1[Starklings]: Herramienta para practicar Cairo, basada en Rustlings.

== Conclusión

Starknet ofrece aplicaciones descentralizadas escalables, seguras y economicas, respaldadas por le tecnologia zk-STARK. No es solo sobre tecnologia, Starknet hace enfasis en empoderar a los la comunidada de desarrolladores con herramientas y recursos robustos. Este libro busca guiar a todos esos que desean explorar Starknet, su tecnologia y su filosofia.
